### ISSUE TITLE
Get rid of noise by ignoring unrelated PDF files

### ISSUE THREAD

**Issue by farukcankaya** [TUM-IDP-WS-20/doc#19]
Parent: #2
----

- [x] use data [DATA_RELEVANT.xlsx](https://drive.google.com/file/d/18LcqdyD3t7QigUluxPX4cqTh01uunThj/view?usp=sharing) to ignore unrelated pdf files
- [x] Check the other pdf files that have less than 9 pages
- [x]  Take a group decision to use or not these files as data

**Comment by MelikeSila** [comment]
Hello @farukcankaya ,
There is no any PDF file has less than 9 pages in  DATA_RELEVANT.xlsx file.

Please check the [test](https://colab.research.google.com/drive/171v3hNeaX11LGr40jDvXciPBuqxah1hJ#scrollTo=uy7awNZXmUHx) .

**TODO**
- [x] Check the other pdf files that have less than 9 pages
- [x] Take a group decision to use or not these files as data

**Comment by MelikeSila** [comment]
We are gonna ignore all pdf files less than 10 pages. We took into account the "DATA_RELEVANT.xlsx" file provided by the supervisor. We get in touch with the supervisor and decided to ignore them
